# Setup
title:               Arnav's Weblog
tagline:             ''
# description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://arnavdhamija.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Arnav Dhamija
  url:               shortstheory.github.io
  # email:             markdotto@gmail.com
repository: shortstheory/shortstheory.github.io
# Gems
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
# Custom vars
version:             1.1.0
google_analytics_id: UA-91464572-1

